### ISSUE TITLE
Vdash failed to load    invalid UTF-8

### ISSUE THREAD

**Issue by willief** [happybeing/vdash#10]
Crashed after attempting to reload  without the  -i flag 
```
willie@gagarin:~$ vdash  ~/.safe/node/baby-fleming-nodes/sn-node-*/sn_node.log 
Loading 12 files...
file: /home/willie/.safe/node/baby-fleming-nodes/sn-node-10/sn_node.log
file: /home/willie/.safe/node/baby-fleming-nodes/sn-node-11/sn_node.log
file: /home/willie/.safe/node/baby-fleming-nodes/sn-node-12/sn_node.log
file: /home/willie/.safe/node/baby-fleming-nodes/sn-node-2/sn_node.log
file: /home/willie/.safe/node/baby-fleming-nodes/sn-node-3/sn_node.log
file: /home/willie/.safe/node/baby-fleming-nodes/sn-node-4/sn_node.log
file: /home/willie/.safe/node/baby-fleming-nodes/sn-node-5/sn_node.log
file: /home/willie/.safe/node/baby-fleming-nodes/sn-node-6/sn_node.log
file: /home/willie/.safe/node/baby-fleming-nodes/sn-node-7/sn_node.log
file: /home/willie/.safe/node/baby-fleming-nodes/sn-node-8/sn_node.log
file: /home/willie/.safe/node/baby-fleming-nodes/sn-node-9/sn_node.log
file: /home/willie/.safe/node/baby-fleming-nodes/sn-node-genesis/sn_node.log
stream did not contain valid UTF-8
```

**Comment by happybeing** [comment]
I think there are two likely causes:
- the logs contain an invalid character. That would be a problem in `sn_node`. It's easier to check (by reloading the logs into vdash) so best to look for that first.
- a bug in the library which is reading the logs, maybe a timing issue (as it's quite rare this happens). It didn't used to happen and that library has been updated, so it's a key suspect. This would be much harder to prove and solve so ideally we'd need to find a way to reproduce it consistently but that looks unlikely for now.

**Comment by willief** [comment]
I think we are on option 2 here.
I just loaded all the saved logs into vdash and it loaded OK each time. It must have been something transient , a bug as you mention or possibly instability as I have never run this box so hard before - its only a few months old.     I'll keep an eye out for anything similar.    Possibly close this one now and refer back if need be?

**Comment by willief** [comment]
I got that error again. However seconds later the big box ran out of memory
entirely and froze. So this is from my phone.  So we can probably discount
this last occurrence.
