### ISSUE TITLE
Vdash panics

### ISSUE THREAD

**Issue by willief** [happybeing/vdash#13]
I forgot to add RUST_LOG blah... before the safe node join command.
Is this expected behaviour or is there an underlying problem?

```
willie@gagarin:~$ vdash /home/willie/.safe/node/local-node/
Loading 1 files...
file: /home/willie/.safe/node/local-node/
thread 'main' panicked at 'Unable to read line: Os { code: 21, kind: IsADirectory, message: "Is a directory" }', /home/willie/.cargo/registry/src/github.com-1ecc6299db9ec823/vdash-0.7.3/src/bin/../custom/app.rs:436:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by happybeing** [comment]
Could be a logfile problem, hard to say without  more details on what you did and what's in the relevant logfile.

**Comment by willief** [comment]
I launched it successfully with the same logfile a few mins later.    Happy to close this if you are.

**Comment by happybeing** [comment]
I'll leave it open for now so anyone else stumbling on this message can find it.
