### ISSUE TITLE
please tag releases in git

### ISSUE THREAD

**Issue by jonassmedegaard** [happybeing/vdash#15]
Newest git tag is `0.6.5` but commit messages indicate that newer releases have been more casually intended.

Please formally tag releases - that helps redistributors (like myself, for Debian) to easier notice when you consider code mature enough to progress.

**Comment by happybeing** [comment]
Thanks @jonassmedegaard. I thought adding a tag (eg added v0.7.4 recently) was sufficient but it looks like I've not pushed them to the repo. So many potholes 😄

**Comment by happybeing** [comment]
Done.
