### ISSUE TITLE
crate chrono might cause segfault

### ISSUE THREAD

**Issue by jonassmedegaard** [happybeing/vdash#16]
I notice that this project uses the crate `chrono` and that [others mention a CVE filed against that and recommend migrating to crate time](https://github.com/interledger-rs/interledger-rs/issues/737#issue-1079949705).

Perhaps sensible here as well to try replace with crate `time`?

**Comment by happybeing** [comment]
Please consider this an issue tracking switch from crate `chrono` to `time`.

**Comment by pinkforest** [comment]
@happybeing There is now new patched version of chrono 0.4.20
https://github.com/rustsec/advisory-db/pull/1306
The new version has pure rust version of localtime_r partying_face
You might want to bump your Cargo.lock for it

**Comment by happybeing** [comment]
Closing as vdash 0.16 is using chrono 0.4.31.
