### ISSUE TITLE
document use of `sn_node --resource-logs`

### ISSUE THREAD

**Issue by jonassmedegaard** [happybeing/vdash#18]
This tool documents needing trace-level logging enabled.

It seems an alternative is to instead enable sn_node option `..resource-logs` and capture stdout from the daemon.
That alternative then works only on systems able to capture stdout (i.e. not some Windows environments), but for those systems capable it is probably helpful to lighten system load.

**Comment by happybeing** [comment]
Closing this for now, but feel free to re-open. 

Log outputs are now adjusted so `vdash` can obtain necessary metrics using default 'info' logging which will reduce use of system disk space.

Other improvements that also assist are `vdash` checkpoints which mean it is generally unnecessary to keep more than the immediate log output file (i.e. no rotated logs) even if `vdash` is restarted. 

Also note that if re-opened, the relevant command line flag is now `--log-output-dest`, and the command has changed from `sn_node` to `safenode`.
