### ISSUE TITLE
"called `Option::unwrap()` on a `None` value"

### ISSUE THREAD

**Issue by flavorel** [happybeing/vdash#29]
Hi,

I cannot start vdash. I am getting the following error : 

C:\Users\MSI>vdash "C:\Users\MSI\AppData\Roaming\safe\launchpad\logs\launchpad_2024-06-24_07-56-46.log"
Loading 1 files...
file: C:\Users\MSI\AppData\Roaming\safe\launchpad\logs\launchpad_2024-06-24_07-56-46.log
thread 'main' panicked at C:\Users\MSI\.cargo\registry\src\index.crates.io-6f17d22bba15001f\vdash-0.17.9\src/bin\..\custom\app.rs:1124:59:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

vdash 0.17.9
Windows 11 (Version : 23H2)

Any idea what went wrong ?
Thanks in advance.

**Comment by happybeing** [comment]
Thanks for the report. Please can you edit your report above to include the version and type of your OS and version of vdash.

**Comment by flavorel** [comment]
Done

**Comment by happybeing** [comment]
Thanks. I can't look immediately but your report is helpful.

Related, several people have had problems getting `vdash` to run at all on Windows. Did you have to do anything other than install Rust?

**Comment by flavorel** [comment]
cargo install vdash

That was pretty much it. :)

**Comment by happybeing** [comment]
Some are having problems with pre-requisites not being found so I'm curious if you have installed those in some way, perhaps with something like Visual Studio? Are you using any tooling that might have installed a linker or VC++ dlls?

**Comment by flavorel** [comment]
Yes, I have installed C++ development requirements through Visual Studio.

**Comment by happybeing** [comment]
Sorry for taking a while to ready your report properly, but the issue is that you are giving vdash the `launchpad` logfile, not a node logfile. The path for Windows should be something like:
```
vdash C:\Users\<USERNAME>\AppData\Roaming\safe\node\*\logs\safenode.log
```
The above is from the [vdash usage](https://github.com/happybeing/vdash#vdash-usage) section of the README.

**Comment by flavorel** [comment]
Thank you for your help. Unfortunately, I have no such "node" folder.

**Comment by happybeing** [comment]
You will have a logs folder for each node somewhere but I don't know where it is located as I don't use Windows. Ask on the forum or discord and if you find it please report back and I'll add it to the README.

**Comment by flavorel** [comment]
Found it ! "C:\ProgramData\safenode\logs\safenode*\safenode.log"
