### ISSUE TITLE
bug: Vdash installation stops with "error[E0658]: use of unstable library feature 'lazy_cell'"

### ISSUE THREAD

**Issue by Voim4** [happybeing/vdash#33]
It went like this: 

Compiling strfmt v0.2.4
   Compiling glob v0.3.1
   Compiling vdash v0.18.0
error[E0658]: use of unstable library feature 'lazy_cell'
 --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vdash-0.18.0/src/bin/../custom/app.rs:8:5
  |
8 | use std::sync::LazyLock;
  |     ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

**Comment by happybeing** [comment]
I think you are using an older version of Rust.

Please check your Rust version with `rustc -V`, report it here and then run `rustup update && cargo install vdash`

**Comment by StephanFA** [comment]
mine is rustc 1.78.0 (9b00956e5 2024-04-29) on Windows 10
